language: node_js
node_js:
  - '8.10.0'
  - '8'
  - '10'
  - '12'
deploy:
  provider: npm
  email: rfobic@gmail.com
  on:
    tags: true
  api_key:
    secure: ZArZGb/qyz2XlRr3SThngIiplmtdM0eNslXQchIMyxeie0IeiW6aLAioMr/tTc/JfZHIAoFGXoFliA3CiZgWk0svSaKGW1aVuWzfc+exOqvxjqhAcf41iniUSCaiuE9gGQU57sXn3yaxXHHMqq8hrXHsdxlRcjwjWPxqw5B7IVQ=
